version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/k-kazuya0926/circleci-101
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: echo $MESSAGE
